version: "3.3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bookstore
    ports:
      - 5444:5432